import { colors, fonts } from "./theme.js";
import { S, sectionTitle, drawDivider } from "./layout.js";
import { safeArray } from "./pdfUtils.js";

export const drawAnalysis = (doc, analysis = {}, scale = 1) => {
  const contentWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const sizes = {
    cardTitle: S(14, scale),
    cardSub: S(9, scale),
    sectionTitle: S(10.5, scale),
    body: S(9.3, scale),
    badge: S(8.3, scale),
  };

  const gap = { afterSectionTitle: 5 * scale, afterItem: 7 * scale, lineGap: 1.1 * scale };

  drawScoreCard(doc, analysis, sizes, contentWidth, scale);

  if (analysis.summary) {
    sectionTitle(doc, "Executive Summary", sizes.sectionTitle, contentWidth, gap);
    doc.font(fonts.regular).fontSize(sizes.body).fillColor(colors.text)
       .text(analysis.summary, { width: contentWidth, lineGap: gap.lineGap });
    doc.moveDown(gap.afterItem / 10);
  }

  bulletSection(doc, "Strengths", analysis.strengths, sizes, contentWidth, gap);
  bulletSection(doc, "Weaknesses", analysis.weaknesses, sizes, contentWidth, gap);

  const skillGap = safeArray(analysis.skillGap);
  if (skillGap.length) {
    sectionTitle(doc, "Skill Gap", sizes.sectionTitle, contentWidth, gap);
    skillGap.forEach((item) => {
      const skill = typeof item === "string" ? item : item.skill;
      const severity = (typeof item === "object" && item.severity) || "medium";
      doc.font(fonts.bold).fontSize(sizes.body).fillColor(colors.text)
         .text(skill || "", { continued: true, width: contentWidth });
      doc.font(fonts.regular).fillColor(colors.muted).text(`   —   ${severity} priority`, { width: contentWidth });
      doc.moveDown(0.12);
    });
    doc.moveDown(gap.afterItem / 10);
  }

  badgeSection(doc, "Matched Keywords", analysis.keywordMatch, sizes, contentWidth, gap, colors.accent);
  badgeSection(doc, "Missing Keywords", analysis.missingKeywords, sizes, contentWidth, gap, "#b91c1c");

  bulletSection(doc, "ATS Tips", analysis.atsTips, sizes, contentWidth, gap);
  bulletSection(doc, "Learning Roadmap", analysis.learningRoadmap, sizes, contentWidth, gap);

  doc.moveDown(0.3);
  drawDivider(doc, contentWidth, colors.border);
  doc.font(fonts.regular).fontSize(S(7.3, scale)).fillColor(colors.muted)
     .text("Generated by DevCane AI Resume Analyzer", { width: contentWidth, align: "center" });
};

function drawScoreCard(doc, analysis, sizes, width, scale) {
  const x = doc.x;
  const y = doc.y;
  const h = 58 * scale;

  doc.roundedRect(x, y, width, h, 10).fillColor(colors.calloutBg).fill();
  doc.roundedRect(x, y, width, h, 10).strokeColor(colors.border).lineWidth(1).stroke();

  const r = 22 * scale;
  const cx = x + 16 * scale + r;
  const cy = y + h / 2;

  doc.circle(cx, cy, r).lineWidth(2.5).strokeColor(colors.text).stroke();
  doc.font(fonts.bold).fontSize(S(13, scale)).fillColor(colors.text)
     .text(String(Math.round(Number(analysis.matchScore) || 0)), cx - r, cy - S(6, scale), { width: r * 2, align: "center" });

  const textX = cx + r + 14 * scale;
  const textWidth = width - (textX - x) - 10 * scale;

  doc.font(fonts.bold).fontSize(sizes.cardTitle).fillColor(colors.text)
     .text("Resume Analysis Report", textX, y + 10 * scale, { width: textWidth });
  doc.font(fonts.regular).fontSize(sizes.cardSub).fillColor(colors.muted)
     .text("ATS-style review with strengths, weaknesses, missing keywords and a roadmap.", textX, doc.y + 2, { width: textWidth });

  doc.x = x;
  doc.y = y + h + 10 * scale;
  doc.fillColor(colors.text);
}

function bulletSection(doc, title, items, sizes, width, gap) {
  const list = safeArray(items);
  if (!list.length) return;
  sectionTitle(doc, title, sizes.sectionTitle, width, gap);
  doc.font(fonts.regular).fontSize(sizes.body).fillColor(colors.subtitle);
  doc.list(list, doc.x, doc.y, { width, bulletRadius: 1.4, textIndent: 10, lineGap: gap.lineGap });
  doc.fillColor(colors.text);
  doc.moveDown(gap.afterItem / 10);
}

function badgeSection(doc, title, items, sizes, width, gap, color) {
  const list = safeArray(items);
  if (!list.length) return;
  sectionTitle(doc, title, sizes.sectionTitle, width, gap);
  drawBadgeRow(doc, list, sizes.badge, width, color);
  doc.moveDown(gap.afterItem / 10);
}

function drawBadgeRow(doc, items, size, maxWidth, color) {
  const paddingX = 6, paddingY = 3, gapX = 5, gapY = 5;
  const startX = doc.x;
  let x = startX;
  let y = doc.y;

  doc.font(fonts.regular).fontSize(size);

  items.forEach((item) => {
    const label = String(item);
    const w = doc.widthOfString(label) + paddingX * 2;
    const h = size + paddingY * 2;

    if (x + w > startX + maxWidth) {
      x = startX;
      y += h + gapY;
    }

    doc.roundedRect(x, y, w, h, h / 2).strokeColor(color).lineWidth(0.75).stroke();
    doc.fillColor(color).text(label, x + paddingX, y + paddingY, { lineBreak: false });

    x += w + gapX;
  });

  doc.x = startX;
  doc.y = y + size + paddingY * 2 + 4;
  doc.fillColor(colors.text);
}