import PDFDocument from "pdfkit";
import { bg } from "../../utils/pdf/pdfHelpers.js";
import { drawHeader } from "../../utils/pdf/pdfHeader.js";
import { drawScoreCard } from "../../utils/pdf/pdfCards.js";
import { summarySection, bulletSection, skillGapSection, keywordSection, roadmapSection } from "../../utils/pdf/pdfSections.js";
import { C } from "../../utils/pdf/pdfTheme.js";



const drawFinalFooter = (doc) => {
  const y = doc.y + 24;
  const pageW = doc.page.width;
  doc.strokeColor(C.border).lineWidth(0.6)
    .moveTo(40, y).lineTo(pageW - 40, y).stroke();
  doc.fillColor(C.muted).font("Helvetica").fontSize(9)
    .text("Generated by Devcane AI Resume Analyzer", 40, y + 10,
      { width: pageW - 80, align: "center" });
};

export const generateReportPdf = (analysis, res) => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 40,
    bufferPages: true,
    autoFirstPage: true,
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${analysis.filename.replace(/\.[^/.]+$/, "")}-report.pdf"`
  );

  doc.pipe(res);

  bg(doc);

  drawHeader(doc, analysis);
  drawScoreCard(doc, analysis.matchScore);
  summarySection(doc, analysis.summary);
  bulletSection(doc, "Strengths", analysis.strengths, C.green);
  bulletSection(doc, "Areas To Improve", analysis.weaknesses, C.red);
  skillGapSection(doc, analysis.skillGap);
  keywordSection(doc, "Matched Keywords", analysis.keywordMatch);
  keywordSection(doc, "Missing Keywords", analysis.missingKeywords);
  bulletSection(doc, "ATS Recommendations", analysis.atsTips, C.blue);
  roadmapSection(doc, analysis.learningRoadmap);

  drawFinalFooter(doc);


  const range = doc.bufferedPageRange();
  const lastIdx = range.start + range.count - 1;

  if (range.count > 1) {
    doc.switchToPage(lastIdx);
 
    if (doc.y < 80) {
     
      doc.rect(0, 0, doc.page.width, doc.page.height).fill(C.bg);
    }
  }


  const finalRange = doc.bufferedPageRange();
  const visibleCount = doc.y < 80 ? finalRange.count - 1 : finalRange.count;

  for (let i = 0; i < finalRange.count; i++) {
    doc.switchToPage(finalRange.start + i);
    
    if (i === finalRange.count - 1 && doc.y < 80) continue;
    doc.fillColor(C.border).font("Helvetica").fontSize(8)
      .text(`${i + 1} / ${visibleCount}`,
        doc.page.width - 65, doc.page.height - 30,
        { width: 40, align: "right" });
  }

  doc.end();
};