import { useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { FiArrowLeft, FiSettings, FiUpload } from "react-icons/fi";
import { BsStars } from "react-icons/bs";
import { useResumeAnalysis } from "../services/ResumeAnalysis.context";

import ScoreCard from "../components/ScoreCard";
import SummaryCard from "../components/SummaryCard";
import StrengthCard from "../components/StrengthCard";
import WeaknessCard from "../components/WeaknessCard";
import SkillGapCard from "../components/SkillGapCard";
import KeywordCard from "../components/KeywordCard";
import ATSRecommendationCard from "../components/ATSRecommendationCard";
import RoadmapCard from "../components/RoadmapCard";
import DownloadButton from "../components/DownloadButton";

const ResumeAnalysis = () => {
  const { id } = useParams();
  const { loading, analysis, getAnalysis } = useResumeAnalysis();

  useEffect(() => { if (id) getAnalysis(id); }, [id]);

  if (loading) return (
    <div className="min-h-screen bg-[#03070f] flex items-center justify-center">
      <div className="flex flex-col items-center gap-4">
        <div className="h-14 w-14 rounded-2xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
          <Loader2 size={24} className="animate-spin text-blue-400" />
        </div>
        <p className="text-slate-500 text-sm">Analyzing your resume...</p>
      </div>
    </div>
  );

  if (!analysis) return (
    <div className="min-h-screen bg-[#03070f] flex items-center justify-center px-4 text-center">
      <div>
        <p className="text-white font-bold text-lg mb-2">Failed to load report</p>
        <p className="text-slate-500 text-sm mb-5">Please try again or upload a new resume.</p>
        <Link to="/resume-upload" className="bg-blue-600 hover:bg-blue-500 text-white px-5 py-2.5 rounded-xl text-sm font-bold transition">
          Try Again
        </Link>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#03070f] text-white">

      {/* Background */}
      <div className="fixed inset-0 -z-10 pointer-events-none">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-blue-500/4 blur-[120px] rounded-full" />
        <div className="absolute bottom-0 right-0 w-[400px] h-[300px] bg-[#22c55e]/4 blur-[100px] rounded-full" />
        <div className="absolute inset-0 opacity-[0.015] bg-[linear-gradient(to_right,#ffffff_1px,transparent_1px),linear-gradient(to_bottom,#ffffff_1px,transparent_1px)] bg-[size:40px_40px]" />
      </div>

      {/* ── Sticky top bar ── */}
      <div className="sticky top-0 z-20 flex items-center justify-between px-4 sm:px-6 py-4 bg-[#03070f]/80 backdrop-blur-xl border-b border-[#1a2d4a]">
        <Link to="/resume-upload"
          className="inline-flex items-center gap-2 rounded-xl border border-[#1a2d4a] bg-[#060d1a] px-3 sm:px-4 py-2 sm:py-2.5 text-xs sm:text-sm font-semibold text-slate-300 hover:text-white hover:border-blue-500/30 transition">
          <FiArrowLeft size={15} /> Back
        </Link>
        <Link to="/settings"
          className="inline-flex items-center gap-2 rounded-xl border border-[#1a2d4a] bg-[#060d1a] px-3 sm:px-4 py-2 sm:py-2.5 text-xs sm:text-sm font-semibold text-slate-300 hover:text-white hover:border-blue-500/30 transition">
          <FiSettings size={15} /> Settings
        </Link>
      </div>

      <div className="relative z-10 max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-10">

        {/* ── Page header ── */}
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-8">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-blue-500/20 bg-blue-500/8 text-blue-400 text-[10px] font-bold uppercase tracking-widest mb-3">
              <BsStars size={10} /> AI Resume Analysis
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-white">Resume Report</h1>
            <p className="text-slate-500 text-sm mt-1">
              Generated by Devcane AI
              {analysis.filename && <span className="text-slate-600"> · {analysis.filename}</span>}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <DownloadButton id={analysis._id} />
            <Link to="/resume-analysis" className="inline-flex items-center gap-2 px-4 sm:px-5 py-2 sm:py-2.5 rounded-xl bg-[#22c55e] hover:bg-[#16a34a] text-white text-xs sm:text-sm font-bold transition hover:shadow-lg hover:shadow-[#22c55e]/20">
              <FiUpload size={14} /> Upload Again
            </Link>
          </div>
        </div>

        {/* ── Score ── */}
        <ScoreCard score={analysis.matchScore} />

        {/* ── Summary ── */}
        <div className="mt-5"><SummaryCard summary={analysis.summary} /></div>

        {/* ── Grid ── */}
        <div className="grid sm:grid-cols-2 gap-5 mt-5">
          <StrengthCard strengths={analysis.strengths} />
          <WeaknessCard weaknesses={analysis.weaknesses} />
          <SkillGapCard skillGap={analysis.skillGap} />
          <KeywordCard matched={analysis.keywordMatch} missing={analysis.missingKeywords} />
          <ATSRecommendationCard tips={analysis.atsTips} />
          <RoadmapCard roadmap={analysis.learningRoadmap} />
        </div>

        {/* ── Footer ── */}
        <div className="mt-10 pt-6 border-t border-[#1a2d4a] text-center">
          <p className="text-slate-700 text-xs">Generated by Devcane AI Resume Analyzer</p>
        </div>
      </div>
    </div>
  );
};

export default ResumeAnalysis;