import { useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { FiUpload } from "react-icons/fi";
import { BsStars } from "react-icons/bs";

import GlowBackground from "../../shared/components/GlowBackground";
import TopBar from "../../shared/components/TopBar";

import ScoreCard from "../components/ScoreCard";
import SummaryCard from "../components/SummaryCard";
import StrengthCard from "../components/StrengthCard";
import WeaknessCard from "../components/WeaknessCard";
import SkillGapCard from "../components/SkillGapCard";
import KeywordCard from "../components/KeywordCard";
import ATSRecommendationCard from "../components/ATSRecommendationCard";
import RoadmapCard from "../components/RoadmapCard";
import DownloadButton from "../components/DownloadButton";
import { useResumeAnalysis } from "../services/Analysis.context";

const ResumeAnalysis = () => {
  const { id } = useParams();
  const { loading, analysis, getAnalysis } = useResumeAnalysis();

  useEffect(() => {
    if (id) getAnalysis(id);
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#03070f] flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="h-14 w-14 rounded-2xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
            <Loader2 size={24} className="animate-spin text-blue-400" />
          </div>
          <p className="text-slate-500 text-sm">Analyzing your resume...</p>
        </div>
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="min-h-screen bg-[#03070f] flex items-center justify-center px-4 text-center">
        <div>
          <p className="text-white font-bold text-lg mb-2">Failed to load report</p>
          <p className="text-slate-500 text-sm mb-5">Please try again or upload a new resume.</p>
          <Link
            to="/resume-analysis"
            className="bg-blue-600 hover:bg-blue-500 text-white px-5 py-2.5 rounded-xl text-sm font-bold transition"
          >
            Try Again
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#03070f] text-white">
      <GlowBackground />
      <TopBar backTo="/resume-analysis" backLabel="Back" />

      <div className="relative z-10 max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-10">
       
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-8">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-blue-500/20 bg-blue-500/8 text-blue-400 text-[10px] font-bold uppercase tracking-widest mb-3">
              <BsStars size={10} /> Resume Analysis
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-white">Resume Report</h1>
            <p className="text-slate-500 text-sm mt-1">
              Generated by Devcane AI
              {analysis.filename && <span className="text-slate-600"> · {analysis.filename}</span>}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <DownloadButton id={analysis._id} />
            <Link
              to="/resume-analysis"
              className="inline-flex items-center gap-2 px-4 sm:px-5 py-2 sm:py-2.5 rounded-xl bg-[#22c55e] hover:bg-[#16a34a] text-white text-xs sm:text-sm font-bold transition hover:shadow-lg hover:shadow-[#22c55e]/20"
            >
              <FiUpload size={14} /> Upload Again
            </Link>
          </div>
        </div>

        
        <ScoreCard score={analysis.matchScore} />

        <div className="mt-5">
          <SummaryCard summary={analysis.summary} />
        </div>

        <div className="grid sm:grid-cols-2 gap-5 mt-5">
          <StrengthCard strengths={analysis.strengths} />
          <WeaknessCard weaknesses={analysis.weaknesses} />
          <SkillGapCard skillGap={analysis.skillGap} />
          <KeywordCard matched={analysis.keywordMatch} missing={analysis.missingKeywords} />
          <ATSRecommendationCard tips={analysis.atsTips} />
          <RoadmapCard roadmap={analysis.learningRoadmap} />
        </div>

        <div className="mt-10 pt-6 border-t border-[#1a2d4a] text-center">
          <p className="text-slate-700 text-xs">Generated by Devcane AI Resume Analyzer</p>
        </div>
      </div>
    </div>
  );
};

export default ResumeAnalysis;